package com.example.galleryapp

import io.objectbox.annotation.Backlink
import io.objectbox.annotation.Entity
import io.objectbox.annotation.HnswIndex
import io.objectbox.annotation.Id
import io.objectbox.relation.ToMany
import io.objectbox.relation.ToOne
import io.objectbox.annotation.VectorDistanceType // Import this


// Stores MobileCLIP vectors of images to allow contextual text searches.
@Entity
data class ContextImageEntity(
    @Id var id: Long = 0,
    var imageUri: String = "",

    // Delegate the math directly to ObjectBox
    @HnswIndex(
//Machine learning models output vectors of a fixed, specific size. This line tells ObjectBox exactly how large the array
//will be. In this case, the MobileCLIP model generates exactly 512 decimal numbers to describe the contents of any given image.
        dimensions = 512,
// This tells the database how to calculate the similarity between two vectors. When you type a search
// query (like "a dog on a beach"), the app converts your text into its own 512-dimension vector.
// ObjectBox then compares the text vector to all the image clipVectors in the database using Cosine Distance
// (measuring the angle between the vectors in 512-dimensional space). Vectors that point in the same direction
// have a very small angle between them, meaning the image perfectly matches the text prompt.
        distanceType = VectorDistanceType.COSINE
    )
    var clipVector: FloatArray? = null
)

// Stores the original image file path and its last modified date.
@Entity
data class ImageEntity(
    @Id var id: Long = 0,
    var imageUri: String = "",
    var dateModified: Long = 0
) {
    lateinit var faces: ToMany<FaceEntity>
}

// Groups identical FaceEntity records together under one person.
@Entity
data class PersonEntity(
    @Id var id: Long = 0,
    var name: String = "Unknown Person",
    var coverFaceImagePath: String = "" // The thumbnail to display in your BottomSheet
) {
    @Backlink(to = "person") // links to faceEntity's person. FaceEntity has a personID column
    lateinit var faces: ToMany<FaceEntity> //In ObjectBox, ToMany is a special type of variable that acts almost exactly like a
// standard Kotlin MutableList or ArrayList. Every time your app groups a recognized face into a cluster, ObjectBox
// silently adds that FaceEntity to this specific faces list. Instead, it waits until the exact moment you ask for the photos
// (like when you tap a person's profile), and then it quickly fetches just those specific faces from the database.
// When you write person.faces, ObjectBox simply runs a lightning-fast background search that says: "Find every Face in the database where
// the personId matches this person." It builds the list dynamically on the fly using the tiny 8-byte pointers that already exist inside the FaceEntity records.
}

// Stores cropped face vectors and bounding boxes.
@Entity
data class FaceEntity(
    @Id var id: Long = 0,
    // the 512-dimension mathematical array (embedding) generated by your machine learning model
    @HnswIndex(dimensions = 512) var faceVector: FloatArray? = null,
    var boundingBox: String = "",

    //When the SCRFD model detects a face in your massive original photo, the app physically cuts that face out and saves
    //it as a tiny, cropped JPEG in the app's internal storage. This property is just the text path to where that tiny image is saved.
    var faceImagePath: String = ""
) {
    // A direct database link (ToOne<ImageEntity>) pointing back to the original, uncropped photo that this face was pulled from.
    lateinit var image: ToOne<ImageEntity>
    // A direct database link (ToOne<PersonEntity>) pointing to the cluster profile this face was eventually grouped into by the DBSCAN algorithm.
    lateinit var person: ToOne<PersonEntity> // NEW: Links this specific face to a master Person
}

//Acts as a receipt for undoing profile merges.
@Entity
data class MergeHistoryEntity(
    @Id var id: Long = 0,
    var primaryPersonId: Long = 0,
    var primaryCoverPath: String = "", // To display Face 1 in the UI
    var mergedCoverPath: String = "",  // To display Face 2 in the UI
    var faceIdsMoved: String = ""      // A comma-separated list of the exact faces we moved
)